// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace badgeevent
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class BadgeEvent : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""BadgeEvent"",""namespace"":""badgeevent"",""fields"":[{""name"":""id"",""type"":""string""},{""name"":""name"",""type"":""string""},{""name"":""userId"",""type"":""string""},{""name"":""displayName"",""type"":""string""},{""name"":""reputation"",""type"":""string""},{""name"":""upVotes"",""type"":""int""},{""name"":""downVotes"",""type"":""int""},{""name"":""processedDate"",""type"":""string""}]}");
		private string _id;
		private string _name;
		private string _userId;
		private string _displayName;
		private string _reputation;
		private int _upVotes;
		private int _downVotes;
		private string _processedDate;
		public virtual Schema Schema
		{
			get
			{
				return BadgeEvent._SCHEMA;
			}
		}
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				this._id = value;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public string userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				this._userId = value;
			}
		}
		public string displayName
		{
			get
			{
				return this._displayName;
			}
			set
			{
				this._displayName = value;
			}
		}
		public string reputation
		{
			get
			{
				return this._reputation;
			}
			set
			{
				this._reputation = value;
			}
		}
		public int upVotes
		{
			get
			{
				return this._upVotes;
			}
			set
			{
				this._upVotes = value;
			}
		}
		public int downVotes
		{
			get
			{
				return this._downVotes;
			}
			set
			{
				this._downVotes = value;
			}
		}
		public string processedDate
		{
			get
			{
				return this._processedDate;
			}
			set
			{
				this._processedDate = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.id;
			case 1: return this.name;
			case 2: return this.userId;
			case 3: return this.displayName;
			case 4: return this.reputation;
			case 5: return this.upVotes;
			case 6: return this.downVotes;
			case 7: return this.processedDate;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.id = (System.String)fieldValue; break;
			case 1: this.name = (System.String)fieldValue; break;
			case 2: this.userId = (System.String)fieldValue; break;
			case 3: this.displayName = (System.String)fieldValue; break;
			case 4: this.reputation = (System.String)fieldValue; break;
			case 5: this.upVotes = (System.Int32)fieldValue; break;
			case 6: this.downVotes = (System.Int32)fieldValue; break;
			case 7: this.processedDate = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
